# Site settings
title:              Danial Hagemann
#subtitle: Some subtitle
email:              mail@danialhagemann.de
description:        This is my private website.
baseurl:            ""
url:                "https://test.danialhagemann.de"
github_username:    DaHaCoder
#cover: "/assets/header_image.jpg"
#logo: "/assets/nr-logo.jpg"
#avatar: "/assets/headshot.jpg"

# Build settings
markdown: kramdown

kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

    katex:
      rendering_options:
        macros:
          # sets
          # "\\N": "\\mathbb{N}"
          # "\\Z": "\\mathbb{Z}"
          # "\\Q": "\\mathbb{Q}"
          # "\\R": "\\mathbb{R}"
          "\\C": "\\mathbb{C}"
          # # math roman
          # "\\D": "\\mathrm{d}"
          # "\\E": "\\mathrm{e}"
          # "\\I": "\\mathrm{i}"
          # vectors and operations on R³
          # "\\vb": "\\boldsymbol{#1}"                     # vector italic
          # "\\vu": "\\hat{\\boldsymbol{#1}}"              # unit vector italic
          # "\\vdot": "\\boldsymbol{\\cdot}"               # dot product
          # "\\cp": "\\boldsymbol{\\times}"                # cross product
          # "\\grad": "\\boldsymbol{\\nabla} #1"           # gradient
          # "\\div": "\\boldsymbol{\\nabla \\cdot #1}"     # divergence
          # "\\curl": "\\boldsymbol{\\nabla \\times #1}"   # curl
          # "\\laplacian": "\\nabla^{2} #1"                # laplacian
          # "\\box": "\\Box #1"                            # box/d'alembertian
          # # derivatives
          # # "\\dd": "\\operatorname{d\\!}"                             # differential d
          # "\\dd": "\\operatorname{d^{#1}\\!{#2}}"                      # powered differential d
          # # "\\dv": "\\frac{\\mathrm{d} #1}{\\mathrm{d} #2}"           # fractional derivative
          # "\\dv": "\\frac{\\mathrm{d}^{#1} #2}{\\mathrm{d} #3^{#1}}"   # powered fractional derivative
          # # "\\pdv": "\\frac{\\partial #1}{\\partial #2}"              # fractional partial derivative
          # "\\pdv": "\\frac{\\partial^{#1} #2}{\\partial #3^{#1}}"      # powered fractional partial derivative


#paginate: 5
#paginate_path: "/page:num/"
#inter_post_navigation: true

plugins:
  - jekyll-paginate
  - jekyll-katex

defaults:
  - scope:
      path: ""
    values:
      author: "Danial Hagemann"

# default settings for 'coding'
  - scope:
      path: ""
      type: coding
    values:
      type: Coding
      permalink: /coding/:path/

# default settings for 'notes'
  - scope:
      path: ""
      type: notes
    values:
      type: Notes
      permalink: /notes/:path/

# default settings for 'physics'
  - scope:
      path: ""
      type: physics
    values:
      type: Physics
      permalink: /physics/:path/

# External gems
#gems:
#  - jekyll-sitemap
#  - jekyll-paginate
#  - jekyll-katex
#  - jemoji
#  - jekyll-seo-tag


exclude:
  - "/vendor/"

# Collections
collections:
  coding:
    output: true
  notes:
    output: true
  physics:
    output: true

#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:

  - name: GitHub
    icon: github
    username: DaHaCoder
    url: https://github.com/DaHaCoder
    desc: Fork me on GitHub
    share: false

  - name: GitLab
    icon: gitlab
    username: DaHaCoder
    url: https://gitlab.com/DaHaCoder
    desc: Fork me on GitLab
    share: true

  - name: Element
    icon: element
    username:
    url:
    desc: Contact me on Element
    share: true

  - name: Threema
    icon: threema
    username:
    url:
    desc: Contact me on Threema
    share: true

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true
